// Category entry
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_CATEGORY_LIST_START = 'SET_CATEGORY_LIST_START';
export const SET_CATEGORY_LIST_END = 'SET_CATEGORY_LIST_END';
export const GET_CATEGORY_TASKS_START = 'GET_CATEGORY_TASKS_START';
export const GET_CATEGORY_TASKS_END = 'GET_CATEGORY_TASKS_END';
export const SET_NEW_TASK_TO_CATEGORY = 'SET_NEW_TASK_TO_CATEGORY';

// Task Form
export const SET_TASKFORM_FIELD = 'SET_TASKFORM_FIELD'
export const POST_NEW_TASK_START = 'POST_NEW_TASK_START'
export const POST_NEW_TASK_END = 'POST_NEW_TASK_END'